[profile.default]
  optimizer = true
  optimizer_runs = 10_000_000
  remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts"]
  solc_version = '0.8.28'
  verbosity = 3

[profile.ci]
  fuzz = { runs = 5000 }
  invariant = { runs = 1000 }
